package com.yangnk.order.mapper;

import com.yangnk.order.model.OmsOrderItem;
import com.yangnk.order.model.OmsOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int countByExample(OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int deleteByExample(OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int insert(OmsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int insertSelective(OmsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    List<OmsOrderItem> selectByExample(OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    OmsOrderItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int updateByExampleSelective(@Param("record") OmsOrderItem record, @Param("example") OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int updateByExample(@Param("record") OmsOrderItem record, @Param("example") OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int updateByPrimaryKeySelective(OmsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Wed May 17 15:25:29 CST 2023
     */
    int updateByPrimaryKey(OmsOrderItem record);

    /**
     * 批量插入OmsOrderItem
     * @param list
     */
    int insertList(@Param("list") List<OmsOrderItem> list);
}